### ISSUE TITLE
"Creating a blank project" documentation not clear for initialise-project-layout

### ISSUE THREAD

**Issue by michaelkohn** [medic/medic-docs#154]
In the [Creating a blank project](https://docs.communityhealthtoolkit.org/docs/application_development/guides/from_scratch/001_introduction.html#creating-a-blank-project) documentation, it gives a few commands to run, but the third command does not work as written (at least for me). I think it's fine to assume a specific scenario ( `local`, for example) and I think we should update the documentation to be more clear.

```bash
mkdir cht-app-tutorials
cd cht-app-tutorials
medic-conf initialise-project-layout
```

When I did `medic-conf initialise-project-layout`, it gave me an error. 

<img width="927" alt="Screen Shot 2019-11-11 at 12 55 06 PM" src="https://user-images.githubusercontent.com/10096985/68578153-8319ff00-0482-11ea-9399-62c168106af0.png">

<img width="927" alt="Screen Shot 2019-11-11 at 12 57 16 PM" src="https://user-images.githubusercontent.com/10096985/68578321-cecca880-0482-11ea-9d5f-ae329b97e8db.png">

If I do `medic-conf --local initialise-project-layout` it worked fine (with a few warnings).
<img width="927" alt="Screen Shot 2019-11-11 at 12 55 58 PM" src="https://user-images.githubusercontent.com/10096985/68578224-a3e25480-0482-11ea-92b9-18babb1dcb75.png">

**Comment by SCdF** [comment]
@michaelkohn this has been fixed in the master of medic-conf, but I had forgotten to release it!

@garethbowen / @kennsippell what is the process for releasing a minor of medic-conf these days?

**Comment by garethbowen** [comment]
There are some instructions here: https://github.com/medic/medic-conf/#releasing

**Comment by SCdF** [comment]
@garethbowen I meant more around decisions on when to cut releases. If I can just cut whenever I want that works for me.

@michaelkohn as you found the ticket that fixes this I'm going to close this ticket. The existing ticket is in AT, so once it makes it through that we can cut another release of medic-conf.
