### ISSUE TITLE
API  / Interoperability documentation

### ISSUE THREAD

**Issue by MaxDiz** [medic/medic-docs#189]
As a partner, I need clear documentation on how to interact with CHT data from outside applications so I can extend the platform by integrating with complimentary tools. 

Ideas for documentation that would be useful:
- API endpoints
- convention(s) followed (ie REST)
- rate limiting on data requests
- authentication requirements
- data formats and translatable values (ie language, numerical, date)
- testing protocol
- Identifier schemes for mapping metadata objects
- user profile requirements for adding/deleting objects
- validating payloads and data element constraints

cc: @ranjuts @kennsippell

**Comment by garethbowen** [comment]
We have fairly solid API documentation here: https://github.com/medic/cht-core/blob/master/api/README.md

Potentially it's not the right place for it any more, or it needs to be linked to more. Otherwise, I think it covers most of your points.

**Comment by MaxDiz** [comment]
sweet! Didn't see it when I searched. We can move it over to the documentation site. 

Closing this issue.
