### ISSUE TITLE
Define documentation site functional requirements

### ISSUE THREAD

**Issue by MaxDiz** [medic/medic-docs#193]
The CHT has an initial draft of the [CHT documentation site](https://docs.communityhealthtoolkit.org/) ([and GH repo](https://github.com/medic/medic.github.io)) up and running. It uses Jekyll, primarily because of the built-in integration with Github Pages. The template is cumbersome, especially for the index, and not well suited to our needs. We are experiencing some challenges with layout, missing key functionality, etc, and have decided to explore alternative tooling options. 

Documentation site requirements and priorities are below. Please add to this ticket

**Easily navigable**
- table of contents/index (must have)
- hierarchy- headings and subheadings. Link to any heading (must have)
- Same page appear multiple times in table of contents (very nice to have)
- Search for both google and internal doc site (very nice to have)
- Tagging for related or prerequisite docs (must have)
- Some kind of app versioning support
*Option 1 - Annotation to indicate features added/removed by version (must have)
*Option 2 - Some sort of tooling support for changes between versions (not required at this time)

**Content types support**
- Markdown (must have)
- Text / Functional description (must have)
- Multimedia- screenshots, gifs, video demos, step-by-step tutorials (must have)
- Code blocks (must have)
- Tables (must have)
- Tutorial modules- bite-sized education/learning opportunities pulling from multiple pieces of information across the platform (nice to have)

**Embedded assistance** - integrate with CHT technical support forum - disqus platform (very nice to have)

**Information portability** to complimentary platforms, and ownership/control (very nice to have)

**Support for language translation** (must have; open to 3rd party services)

**Usable offline** (nice to have)

**Easy to contribute regardless of technical capabilities** should be friendly for all team members to contribute. Github requires some training, but not insurmountable. Are there other good options to consider? (must have)

**Single sign-on** (OAuth) (very nice to have)

**Comment by MaxDiz** [comment]
@abbyad looking for your final review on this issue. It's a blocker to #196 which I would like to assign to a volunteer team member(s) tomorrow

**Comment by abbyad** [comment]
Looks good! 

Adding a nice-to-have is matching or complementing existing CHT and/or Medic branding.
