### ISSUE TITLE
Review and integrate currently available documentation into the new doc site for initial launch

### ISSUE THREAD

**Issue by MaxDiz** [medic/medic-docs#195]
We have compiled a [comprehensive list of existing CHT documentation](https://docs.google.com/document/d/1sirNlpRTkQWOxnQGhm2rS6LdTH-8xwwE-Ik-E-eGacY/edit#). It needs to be reviewed and integrated into the revised site index (#194). During the review process we should:

- de-duplicate existing resource information
- work out which existing documentation resources can be ported directly to the documentation site
- identify required improvements to existing documentation resources before they can be added to the documentation site

**Comment by MaxDiz** [comment]
@abbyad please add directions for where and how to organize documentation information once #194 is done

**Comment by MaxDiz** [comment]
The bulk of the resource list that we created at squad kickoff has been integrated into the [current working version of the site index](https://docs.google.com/document/d/1oa77_SxVlTmi3NAhYw9BaZZVthk-Lwl4--SAi-eY9MU/edit#)

There are two big chunks of content to be reviewed and parsed/consolidated, before transitioning to markdown. It's not currently clear how we want to organize this information for the documentation site - feature overviews? feature overviews + config? how-to guides? a combination of all of these?

**Feature Information**
- [Current feature list (through June 2019)](https://docs.google.com/document/d/1c0K0RDmz86aREZl9P3e8Z7so9VVQPnBwcMkEzaZDUgg/edit#)
- [Features Overview](https://drive.google.com/drive/u/1/folders/0B5QNr7uSAl90U0I4NkxFZFRNa28)
- [Product education](https://drive.google.com/drive/folders/1hym-TBZf7R9F22Ck-Wc6SKSvFH32xNxA )
- [Version-by-version release summary](https://docs.google.com/spreadsheets/d/1yJHdSJTa4y4veAwLR_sAL9EAgZ6URDtFbYLiCQmGq4k/edit#gid=0)

**Impact dashboards/analytics/data interpretation** (cc: @helizabetholsen)
- Impact monitoring overview
- Impact logic documents for priority use cases
- Example data schema
- Example dashboard
- [Data interpretation](https://docs.google.com/presentation/d/1GHkEWUibEsbgUmplu8Ib-VzwKd15fEBbHBYLuX2k8TE/edit#slide=id.p)

**Comment by MaxDiz** [comment]
**Integrations & Interoperability** resources to review for adding to the site for initial launch:

- [Medic-api](https://github.com/medic/cht-core/blob/master/api/README.md)
- [Outbound push](https://github.com/medic/medic-docs/blob/master/configuration/outbound.md)
- Integrating with SMS aggregators ex/ [Africa’s Talking](https://github.com/medic/medic-docs/blob/master/configuration/africas-talking.md) + [workflow diagram](https://docs.google.com/presentation/d/1vW3lVD5cfBJd-wn5KTah1zGJ1La9n96URsNjxLHjEjM/edit?ts=5d3fec7b#slide=id.p)
- Integrating with DHIS2- [config](https://github.com/medic/medic-docs/blob/master/configuration/dhis-integration.md) + user education (coming in v3.9 from Michael)

**Comment by MaxDiz** [comment]
**CHT Core Framework** resources to review for adding to the site for initial launch:

- [Database schema conventions](https://github.com/medic/medic-docs/blob/master/development/db-schema.md)
- [CHT versions currently supported](https://github.com/medic/medic-docs/blob/master/installation/supported-software.md)
- [Contributing](https://github.com/medic/cht-core/blob/cc873339287266e19ed8b7367a00ebd8d09c69ef/CONTRIBUTING.md)

**Comment by MaxDiz** [comment]
**Design System** resources to review for adding to the site for initial launch:

-[icon library](https://github.com/medic/icon-library)
- [user personas](https://github.com/medic/cht-personas) - some personas are in draft form so may need to be selective about which ones to add for launch
- [configuration best practices](https://docs.google.com/document/d/1vWTL9RCnMK-_jFVbQeIlIZIkfyw4DVTO-lxu6vCHieo/edit#heading=h.7oiispqg4kxk) - not sure if complete; needs converted to markdown, also some overlap with this Developer resource that is frequently referenced by contributors

**Comment by MaxDiz** [comment]
**Targets** resources to review for adding to the site for initial launch:
- Updated target detail from [supervisor education](https://docs.google.com/presentation/d/1gHRzPl_goijbsEDBSVBCTS_QoJlXnYhCo92nbgtZeNc/edit#slide=id.p) (v3.9 from Mareme - in progress)

**Comment by MaxDiz** [comment]
**Tasks** resources to review for adding to the site for initial launch:
- update from https://github.com/medic/cht-core/issues/5776 (completed in v3.9)

**Comment by MaxDiz** [comment]
**Getting Started** resources to review for adding to the site for initial launch:
- Hierarchies[updated info from v3.7](https://docs.google.com/presentation/d/1y4E4SXwQCWOhOTntADQ8UG1o9aNIrylFGjWoJ-U2eNc/edit#slide=id.g64dedc98b5_0_299)

**Comment by MaxDiz** [comment]
**Getting Started How-to Guide** ("Getting Your Feet Wet")

https://github.com/medic/medic.github.io/blob/master/docs/application_development/guides/from_scratch/001_introduction.md#getting-our-feet-wet

**Comment by MaxDiz** [comment]
**Messaging** resources to review for adding to the site for initial launch:
- [messaging states](https://github.com/medic/medic-docs/blob/master/user/message-states.md)

**Comment by abbyad** [comment]
Updated the comments above so that we can check the items off as we go.

**Comment by smbuthia** [comment]
@abbyad would it be possible to add new (or remove outdated) documentation through pull requests or will this be possible later?

**Comment by abbyad** [comment]
Yes, updates are possible through commits or PRs to the master branch.

**Comment by abbyad** [comment]
I completed another pass which covers most of the docs listed above that were in medic-docs.

**Comment by MaxDiz** [comment]
completed!!!
