### ISSUE TITLE
conversion of existing documentation resources to markdown in preparation for improved site launch

### ISSUE THREAD

**Issue by MaxDiz** [medic/medic-docs#200]
As part of the review of existing documentation (#195) we will work out which documentation resources should be migrated to the improved documentation site. If a resource is in a format other than markdown, it will need to be converted. This issue is to capture all resources that need to be converted to markdown in preparation for documentation site launch.

**Comment by MaxDiz** [comment]
start with the [CHT overview slidedeck](https://static1.squarespace.com/static/5bd25eea65a707ad54c1e8ca/t/5db502b9628b613d418ce7be/1572143837269/Core+Framework+Overview.pdf)

**Comment by MaxDiz** [comment]
@CescaGarrett can you please link to the goog slides version of the CHT overview deck?

**Comment by CescaGarrett** [comment]
@MaxDiz  [here you go! ](https://docs.google.com/presentation/d/1AtFwxpha83Yh73SkLMTVmuYz35h0cCUy6DRc-l1kt0U/edit#slide=id.g433915d87c_0_6)

**Comment by abbyad** [comment]
The CHT overview was converted to Markdown in [this commit](https://github.com/medic/medic.github.io/commit/b1b77757f1640a048ecc5aeb6ed7988028641c23).  All the text except for the reference workflows has been brought in, and restructured to generally fit the new format and doc index. 

Still to do:
- Keep pulling in other content, reorganizing content as needed
- Bring in images
- tweak the language for a doc site vs the slide deck (eg change "we use").

**Comment by MaxDiz** [comment]
completed for initial launch. Additional issues are being created for follow-up items
