### ISSUE TITLE
Change all "http" to "https" in the docs

### ISSUE THREAD

**Issue by bishwas-medic** [medic/medic-docs#3]
In this doc: https://github.com/medic/medic-docs/blob/master/md/install/smssync.md, the URL examples
have "http" instead of "https". This is confusing the PMs or anyone following the guide to setup the SMSsync.

**Comment by SCdF** [comment]
@bishwas-medic I used the power of find and replace to generate this beauty: https://github.com/medic/medic-docs/pull/4

How does that grab you?

**Comment by bishwas-medic** [comment]
IIRC, you are not supposed to branch the docs and projects repo :)
But thanks for the quick response man. Tuskers for you!
