### ISSUE TITLE
releases doc references npm-shrinkwrap

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-docs#31]
> Set the version number from step 1 in medic-webapp kanso.json, package.json, and npm-shrinkwrap.json. If releasing a new major or minor, also set the versions in master to be the next version (e.g. <major>.<minor+1>.0), so that the alpha builds will have the right version.

from https://github.com/medic/medic-docs/blob/master/development/releasing.md

**Comment by garethbowen** [comment]
That's there just in case we need to release an old version of the app one day...
