### ISSUE TITLE
Document forms for people and places

### ISSUE THREAD

**Issue by abbyad** [medic/medic-docs#55]
We could use some more documentation on managing forms for adding and editing contact forms, including [forms/contact/place-types.json](https://github.com/medic/medic-webapp/blob/master/config/standard/forms/contact/place-types.json) and the generic [forms/contact/PLACE_TYPE-create.xlsx](https://github.com/medic/medic-webapp/blob/master/config/standard/forms/contact/PLACE_TYPE-create.xlsx) and PLACE_TYPE-edit.xlsx.

**Comment by garethbowen** [comment]
Delaying for 3.9.0

**Comment by abbyad** [comment]
This was at least partially covered in https://github.com/medic/medic-docs/commit/866a0a72c871c0d542a2b69b8f6eb20a7d309e43, which seems sufficient for now. With a reference app as the default configuration as well, further documentation may not be needed until we include this topic in the new documenation site and have a tutorial for it. Given that, I'll unschedule and close this issue.
