### ISSUE TITLE
Task configuration documentation

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-docs#56]
Including
- an overview of nools and the TaskGenerator
- inputs to the rules
- expected outputs from the rules, including how actions work
- utility functions available on the Utils class

**Comment by garethbowen** [comment]
It looks extensive enough.

@newtewt Is that PR ready for review?

**Comment by newtewt** [comment]
@garethbowen I'd say it's ready for review.

**Comment by garethbowen** [comment]
Assigned the PR to @abbyad for review.

**Comment by abbyad** [comment]
PR approved, assigning to @newtewt to close this issue once it is merged.

**Comment by newtewt** [comment]
Merged the sample config tests PR.
