### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by wtekeu** [medic/medic-docs#82]
https://github.com/medic/medic-docs/blob/master/configuration/replicate.md => 404
The link is from https://github.com/medic/medic-docs .. entry `Replicating with Futon`
Seems to have moved to https://github.com/medic/medic-docs/blob/master/configuration/legacy/replicate.md

**Comment by garethbowen** [comment]
Covered by https://github.com/medic/medic-docs/pull/83

**Comment by abbyad** [comment]
Thanks for highlighting this @wtekeu! Did a bigger pass while I was at it and just merged, so closing this.
